### ISSUE TITLE
[BUG] NTAG 424 DNA (with NDEF data) erroneously detected as DESFire, does not scan

### ISSUE THREAD

**Issue by micolous** [metrodroid/metrodroid#817]
## Description of the issue

Scanning an NTAG 424 DNA containing NDEF data with Metrodroid on Android or JVMCLI returns error:

```
java.lang.IllegalStateException: Unknown status code: 28
```

It looks like the issue is Metrodroid treats anything that responds to a DESFire Get Version command as DESFire:

https://github.com/metrodroid/metrodroid/blob/d485d3fad5ab496565dea3a64713e8cd89932e2b/src/jvmCliMain/kotlin/au/id/micolous/metrodroid/cli/SmartCard.kt#L220-L227

https://github.com/metrodroid/metrodroid/blob/d485d3fad5ab496565dea3a64713e8cd89932e2b/src/commonMain/kotlin/au/id/micolous/metrodroid/card/desfire/DesfireCardReader.kt#L54-L60

It appears GetVersion is actually an _NXP_ command, and that there are many cards (not just DESFire) that can respond to this.

Metrodroid also doesn't try what I think is the NDEF AID (`D2760000850101`), but it wouldn't get to that anyway due to this detection issue.

I'm still investigating, I think Metrodroid needs to either:

* Select DESFire's ISO7816 AID (`D2760000850100`) explicitly, or,
* Find a path in [AN10833 identification procedure](https://www.nxp.com/docs/en/application-note/AN10833.pdf) to make DESFire protocol more selective, possibly parsing `GetVersion` much earlier.

This possibly affects some other NTAG models which run in ISO7816 mode... I need to do some reading and go do some more shopping, as fixing this may be high risk.  I think that `DesfireCard` should be a subclass of `ISO7816Application`, but reshuffling that will also impact serialisation/deserialisation, and we'd end up with a similar bodge like we have for backwards compatibility with old CEPAS dumps.

## For card-specific issues (delete if not applicable)

- Name of the card type: NTAG 424 DNA

## Steps to reproduce

1. Scan NTAG 424 DNA tag

## Expected behaviour

Scans, shows any NDEF data

## Actual behaviour

`java.lang.IllegalStateException: Unknown status code: 28`

## Workarounds (if any)

none

## Device Logs

Trace using jvmcli (using some development branch); but also affects Android in the same way.

Included here as there's no private data:

```
% ./metrodroid-cli smart-card -t
Terminal: ACS ACR122U
>>> ffca000000
<<< 04596032de71809000
>>> 9060000000
<<< 0404023000110591af
>>> 90af000000
<<< 0404020102110591af
>>> 90af000000
<<< 04596032de7180cf28d9552051209100
Sep. 03, 2022 7:36:57 PM au.id.micolous.metrodroid.multi.Log i
INFO: Manufacturing data: <040402300011050404020102110504596032de7180cf28d955205120>
Reading MIFARE DESFire card…
Dumping: (0 / 1)
>>> 906a000000
<<< 911c
Exception in thread "main" java.lang.IllegalStateException: Unknown status code: 28
	at au.id.micolous.metrodroid.card.desfire.DesfireProtocol.sendRequest(DesfireProtocol.kt:139)
	at au.id.micolous.metrodroid.card.desfire.DesfireProtocol.sendRequest(DesfireProtocol.kt:106)
	at au.id.micolous.metrodroid.card.desfire.DesfireProtocol.getAppList(DesfireProtocol.kt:59)
	at au.id.micolous.metrodroid.card.desfire.DesfireCardReader.dumpTag(DesfireCardReader.kt:68)
	at au.id.micolous.metrodroid.cli.SmartCard.dumpTag(SmartCard.kt:221)
	at au.id.micolous.metrodroid.cli.SmartCard.access$dumpTag(SmartCard.kt:61)
	at au.id.micolous.metrodroid.cli.SmartCard$run$card$1.invokeSuspend(SmartCard.kt:157)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at au.id.micolous.metrodroid.cli.SmartCard.run(SmartCard.kt:157)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
	at au.id.micolous.metrodroid.CliKt.main(Cli.kt:298)
```

## Details from About screen:

- Metrodroid version: git master

## Checklist

- [x] The card appears in the "supported cards" list in Metrodroid on my device.
- [x] I have copied all the details from the about screen into this bug.
- [x] For card reading issues, I have exported a card dump from Metrodroid, and can email it privately if needed.
- [x] I have generated an Android bug report ZIP, and can email it privately if needed.

**Comment by micolous** [comment]
I had a chat with phcoder who mentioned there are some old DESFire cards which don't respond to ISO7816-4 SELECT commands.  Digging deeper, [it's also possible to modify the AID used on MIFARE DESFire and Plus cards](https://www.nxp.com/docs/en/application-note/AN11909.pdf), so it's not a reliable to gate DESFire support – the only mechanism is going to be to send a `GetVersion` command and check the response (and hope nothing else also uses that command).
