### ISSUE TITLE
[QUESTION] Building for IOS -- Missing `GPBProtocolBuffers.h`

### ISSUE THREAD

**Issue by otoledan** [metrodroid/metrodroid#839]
When building for IOS (following https://www.metrodroid.org/metrodroid/ios#getting-metrodroid-for-ios`), I was running into some issues around the GPBProtocolBuffers.h file not being found. It seems strange since the dependency on google Protocol buffers should be pulled in when built. I'm not super familiar with xcode, so forgive me if I'm missing something obvious. 

I checked that it's installed on the system:
```
% protoc --version
libprotoc 24.2
```

I'm including the error in xcode for more information.

Thank you in advance!

Error in xcode: 
```
Showing Recent Messages
Exception in thread "main" java.lang.Error: /Users/otoledan/Desktop/metrodroid/proto/build/generated/source/proto/main/objc/Stations.pbobjc.h:13:10: fatal error: 'GPBProtocolBuffers.h' file not found

	at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:192)

	at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.indexDeclarations(Indexer.kt:1206)

	at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.buildNativeIndexImpl(Indexer.kt:1195)

	at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.buildNativeIndexImpl(Indexer.kt:1191)

	at org.jetbrains.kotlin.native.interop.gen.jvm.DefaultPlugin.buildNativeIndex(Plugins.kt:31)

	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:272)

	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:76)

	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:45)

	at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:38)

	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:60)



FAILURE: Build failed with an exception.
```

**Comment by otoledan** [comment]
Fixed by running
```
$ git clone --recursive https://github.com/metrodroid/metrodroid.git
``` 

instruction from main github page
